-- MySQL Script generated by MySQL Workbench
-- Tue Aug  2 12:08:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ebdb
-- -----------------------------------------------------
SET SQL_SAFE_UPDATES = 0;
CREATE DATABASE IF NOT EXISTS ebdb; ## name given from AWS
USE ebdb;
-- -----------------------------------------------------
-- Table `GeneralUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeneralUser` ;

CREATE TABLE IF NOT EXISTS `GeneralUser` (
  `general_user_id` INT NOT NULL AUTO_INCREMENT,
  `ip_address` INT NULL DEFAULT NULL,
  PRIMARY KEY (`general_user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `RegisteredUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RegisteredUser` ;

CREATE TABLE IF NOT EXISTS `RegisteredUser` (
  `registered_user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NULL DEFAULT NULL,
  `password` VARCHAR(64) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `last_name` VARCHAR(30) NULL DEFAULT NULL,
  `username` VARCHAR(20) NULL DEFAULT NULL,
  `general_user_id` INT NOT NULL,
  `about` VARCHAR(1000) NULL DEFAULT NULL,
  `contact` VARCHAR(1000) NULL DEFAULT NULL,
  `is_banned` INT NULL DEFAULT '0',
  `pfp` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`registered_user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `FK_generalUser_registeredUser_idx` (`general_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_generalUser_registeredUser`
    FOREIGN KEY (`general_user_id`)
    REFERENCES `GeneralUser` (`general_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Admin` ;

CREATE TABLE IF NOT EXISTS `Admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`admin_id`, `registered_user_id`),
  INDEX `FK_registeredUser_admin_idx` (`registered_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_registeredUser_admin`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `College`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `College` ;

CREATE TABLE IF NOT EXISTS `College` (
  `college_id` INT NOT NULL AUTO_INCREMENT,
  `college_name` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`college_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `AssociatedCollege`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AssociatedCollege` ;

CREATE TABLE IF NOT EXISTS `AssociatedCollege` (
  `associated_college_id` INT NOT NULL AUTO_INCREMENT,
  `college_id` INT NOT NULL,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`associated_college_id`),
  INDEX `FK_registeredUser_associatedCollege_idx` (`registered_user_id` ASC) VISIBLE,
  INDEX `FK_college_associatedCollege_idx` (`college_id` ASC) VISIBLE,
  CONSTRAINT `FK_college_associatedCollege`
    FOREIGN KEY (`college_id`)
    REFERENCES `College` (`college_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_registeredUser_associatedCollege`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ForumPost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForumPost` ;

CREATE TABLE IF NOT EXISTS `ForumPost` (
  `forum_post_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`forum_post_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ForumReply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForumReply` ;

CREATE TABLE IF NOT EXISTS `ForumReply` (
  `forum_reply_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `posted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`forum_reply_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ForumTies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForumTies` ;

CREATE TABLE IF NOT EXISTS `ForumTies` (
  `forum_ties_id` INT NOT NULL AUTO_INCREMENT,
  `forum_post_id` INT NOT NULL,
  `forum_reply_id` INT NOT NULL,
  PRIMARY KEY (`forum_ties_id`),
  INDEX `FK_forumPost_forumTies_idx` (`forum_post_id` ASC) VISIBLE,
  INDEX `FK_forumReply_forumTies_idx` (`forum_reply_id` ASC) VISIBLE,
  CONSTRAINT `FK_forumPost_forumTies`
    FOREIGN KEY (`forum_post_id`)
    REFERENCES `ForumPost` (`forum_post_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_forumReply_forumTies`
    FOREIGN KEY (`forum_reply_id`)
    REFERENCES `ForumReply` (`forum_reply_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MarketplaceListing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MarketplaceListing` ;

CREATE TABLE IF NOT EXISTS `MarketplaceListing` (
  `marketplace_listing_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `body` VARCHAR(1000) NULL DEFAULT NULL,
  `seller_id` INT NOT NULL,
  `price` VARCHAR(20) NULL DEFAULT NULL,
  `quantity` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`marketplace_listing_id`),
  INDEX `FK_seller_marketplaceListing_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `FK_seller_marketplaceListing`
    FOREIGN KEY (`seller_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment` ;

CREATE TABLE IF NOT EXISTS `Payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(45) NULL DEFAULT NULL,
  `card_number` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ServiceListing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiceListing` ;

CREATE TABLE IF NOT EXISTS `ServiceListing` (
  `service_listing_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`service_listing_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ServiceReply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiceReply` ;

CREATE TABLE IF NOT EXISTS `ServiceReply` (
  `service_reply_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `posted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`service_reply_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Posts` ;

CREATE TABLE IF NOT EXISTS `Posts` (
  `posts_id` INT NOT NULL AUTO_INCREMENT,
  `service_listing_id` INT NULL DEFAULT NULL,
  `service_reply_id` INT NULL DEFAULT NULL,
  `forum_post_id` INT NULL DEFAULT NULL,
  `forum_reply_id` INT NULL DEFAULT NULL,
  `registered_user_id` INT NOT NULL,
  PRIMARY KEY (`posts_id`),
  INDEX `FK_registeredUser_posts_idx` (`registered_user_id` ASC) VISIBLE,
  INDEX `FK_forumPost_posts_idx` (`forum_post_id` ASC) VISIBLE,
  INDEX `FK_forumReply_posts_idx` (`forum_reply_id` ASC) VISIBLE,
  INDEX `FK_serviceListing_posts_idx` (`service_listing_id` ASC) VISIBLE,
  INDEX `FK_serviceReply_posts_idx` (`service_reply_id` ASC) VISIBLE,
  CONSTRAINT `FK_forumPost_posts`
    FOREIGN KEY (`forum_post_id`)
    REFERENCES `ForumPost` (`forum_post_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_forumReply_posts`
    FOREIGN KEY (`forum_reply_id`)
    REFERENCES `ForumReply` (`forum_reply_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_registeredUser_posts`
    FOREIGN KEY (`registered_user_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_serviceListing_posts`
    FOREIGN KEY (`service_listing_id`)
    REFERENCES `ServiceListing` (`service_listing_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_serviceReply_posts`
    FOREIGN KEY (`service_reply_id`)
    REFERENCES `ServiceReply` (`service_reply_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product` ;

CREATE TABLE IF NOT EXISTS `Product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `general_type` VARCHAR(45) NULL DEFAULT NULL,
  `product_image` VARCHAR(2000) NULL DEFAULT NULL,
  `product_condition` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ProductListings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProductListings` ;

CREATE TABLE IF NOT EXISTS `ProductListings` (
  `product_listing_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `marketplace_listing_id` INT NOT NULL,
  PRIMARY KEY (`product_listing_id`),
  INDEX `FK_marketplaceListing_productListings_idx` (`marketplace_listing_id` ASC) VISIBLE,
  INDEX `FK_product_productListings_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_marketplaceListing_productListings`
    FOREIGN KEY (`marketplace_listing_id`)
    REFERENCES `MarketplaceListing` (`marketplace_listing_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_product_productListings`
    FOREIGN KEY (`product_id`)
    REFERENCES `Product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ProductOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProductOrders` ;

CREATE TABLE IF NOT EXISTS `ProductOrders` (
  `product_order_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `buyer_id` INT NOT NULL,
  PRIMARY KEY (`product_order_id`),
  INDEX `FK_buyer_productOrders_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `FK_product_productOrders_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_buyer_productOrders`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `GeneralUser` (`general_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_product_productOrders`
    FOREIGN KEY (`product_id`)
    REFERENCES `Product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction` ;

CREATE TABLE IF NOT EXISTS `Transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `completed_at` TIMESTAMP NULL DEFAULT NULL,
  `payment_id` INT NOT NULL,
  `buyer_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `FK_payment_transaction_idx` (`payment_id` ASC) VISIBLE,
  INDEX `FK_buyer_transaction_idx` (`buyer_id` ASC) VISIBLE,
  CONSTRAINT `FK_payment_transaction`
    FOREIGN KEY (`payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ratings` ;

CREATE TABLE IF NOT EXISTS `Ratings` (
  `ratings_id` INT NOT NULL AUTO_INCREMENT,
  `rating` TINYINT NULL DEFAULT NULL,
  `registered_user_sender_id` INT NOT NULL,
  `transaction_id` INT NULL DEFAULT NULL,
  `registered_user_receiver_id` INT NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `posted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`ratings_id`),
  INDEX `FK_registeredUser_ratings_idx` (`registered_user_sender_id` ASC) VISIBLE,
  INDEX `FK_transaction_ratings_idx` (`transaction_id` ASC) VISIBLE,
  INDEX `FK_registeredUserReceiver_ratings_idx` (`registered_user_receiver_id` ASC) VISIBLE,
  CONSTRAINT `FK_registeredUserReceiver_ratings`
    FOREIGN KEY (`registered_user_receiver_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_registeredUserSender_ratings`
    FOREIGN KEY (`registered_user_sender_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_transaction_ratings`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Receipt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Receipt` ;

CREATE TABLE IF NOT EXISTS `Receipt` (
  `receipt_id` INT NOT NULL AUTO_INCREMENT,
  `transaction_id` INT NOT NULL,
  `buyer_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`receipt_id`),
  INDEX `FK_transaction_receipt_idx` (`transaction_id` ASC) VISIBLE,
  INDEX `FK_buyer_receipt_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `FK_seller_receipt_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `FK_buyer_receipt`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `GeneralUser` (`general_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_seller_receipt`
    FOREIGN KEY (`seller_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_transaction_receipt`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ServiceTies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiceTies` ;

CREATE TABLE IF NOT EXISTS `ServiceTies` (
  `service_ties_id` INT NOT NULL AUTO_INCREMENT,
  `service_listing_id` INT NOT NULL,
  `service_reply_id` INT NOT NULL,
  PRIMARY KEY (`service_ties_id`),
  INDEX `FK_serviceListing_serviceTies_idx` (`service_listing_id` ASC) VISIBLE,
  INDEX `FK_serviceReply_serviceTies_idx` (`service_reply_id` ASC) VISIBLE,
  CONSTRAINT `FK_serviceListing_serviceTies`
    FOREIGN KEY (`service_listing_id`)
    REFERENCES `ServiceListing` (`service_listing_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_serviceReply_serviceTies`
    FOREIGN KEY (`service_reply_id`)
    REFERENCES `ServiceReply` (`service_reply_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ShoppingCart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShoppingCart` ;

CREATE TABLE IF NOT EXISTS `ShoppingCart` (
  `shopping_cart_id` INT NOT NULL AUTO_INCREMENT,
  `buyer_id` INT NOT NULL,
  PRIMARY KEY (`shopping_cart_id`),
  INDEX `FK_buyer_shoppingCart_idx` (`buyer_id` ASC) VISIBLE,
  CONSTRAINT `FK_buyer_shoppingCart`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `GeneralUser` (`general_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ShoppingCartProducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ShoppingCartProducts` ;

CREATE TABLE IF NOT EXISTS `ShoppingCartProducts` (
  `shopping_cart_products_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `shopping_cart_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`shopping_cart_products_id`),
  INDEX `FK_product_shoppingCartProducts_idx` (`product_id` ASC) VISIBLE,
  INDEX `FK_shoppingCart_shoppingCartProducts_idx` (`shopping_cart_id` ASC) VISIBLE,
  CONSTRAINT `FK_product_shoppingCartProducts`
    FOREIGN KEY (`product_id`)
    REFERENCES `Product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_shoppingCart_shoppingCartProducts`
    FOREIGN KEY (`shopping_cart_id`)
    REFERENCES `ShoppingCart` (`shopping_cart_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TransactionItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransactionItems` ;

CREATE TABLE IF NOT EXISTS `TransactionItems` (
  `transaction_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(1000) NULL DEFAULT NULL,
  `price` VARCHAR(20) NULL DEFAULT NULL,
  `quantity` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`transaction_id`, `product_id`),
  INDEX `transaction_items_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `TransactionItems_ibfk_1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transaction` (`transaction_id`)
    ON DELETE CASCADE,
  CONSTRAINT `TransactionItems_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `Product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `UserPayment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserPayment` ;

CREATE TABLE IF NOT EXISTS `UserPayment` (
  `user_payment_id` INT NOT NULL AUTO_INCREMENT,
  `buyer_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  PRIMARY KEY (`user_payment_id`),
  INDEX `FK_payment_userPayment_idx` (`payment_id` ASC) VISIBLE,
  INDEX `FK_buyer_userPayment_idx` (`buyer_id` ASC) VISIBLE,
  CONSTRAINT `FK_buyer_userPayment`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `RegisteredUser` (`registered_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_payment_userPayment`
    FOREIGN KEY (`payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
